const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {fixture}=require('./backend-fixture.cjs');
function roles(){const f=fixture(),team='team-code-for-test-123456789',admin='admin-code-for-test-987654321',hash=s=>crypto.createHash('sha256').update(s).digest('hex');
 f.ctx.PropertiesService={getScriptProperties:()=>({getProperty:k=>({TEAM_KEY_SHA256:hash(team),ADMIN_KEY_SHA256:hash(admin),SPREADSHEET_ID:'test',ALLOWED_EMAILS:'test@example.com'}[k])})};
 Object.assign(f.ctx.Utilities,{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()]});f.setEmail('');
 return {...f,call:(method,input,role='team',overrides={})=>f.ctx.apiRequest({key:role==='admin'?admin:team,actor:role==='admin'?'Valentina':'Vendedor',profile:role,method,input,...overrides})};}
test('administrator is determined by secret on server, never by name or claimed role',()=>{const f=roles();assert.equal(f.call('getData').role,'team');assert.equal(f.call('getData',null,'admin').capabilities.deleteSales,true);assert.throws(()=>f.call('deleteSale',{},'team',{actor:'Administrador',role:'admin'}),/Solo el administrador/);assert.throws(()=>f.call('getData',null,'team',{profile:'admin'}),/perfil seleccionado/);assert.throws(()=>f.ctx.deleteSale({}),/Solo el administrador/);assert.equal(f.ctx.REQUEST_ROLE_,null);});
test('delete affects one line, excludes totals, keeps audit and is safe to retry',()=>{const f=roles(),order=f.order({lines:[{productId:f.p,quantity:2,unitPrice:17060},{productId:f.p2,quantity:1,unitPrice:36690}]});f.call('saveOrder',order);const rows=f.call('getData').sales,row=rows[0];assert.throws(()=>f.call('deleteSale',{id:row.id,version:2,reason:'Duplicada'},'admin'),/cambió/);assert.throws(()=>f.call('deleteSale',{id:row.id,version:1,reason:' '},'admin'),/motivo/);
 f.call('deleteSale',{id:row.id,version:1,reason:'Duplicada'},'admin');const result=f.call('getData');assert.equal(result.sales.length,1);assert.equal(result.sales[0].id,rows[1].id);assert.equal(result.sales[0].total,36690);
 const archived=f.ctx.read_(f.db,'sales').find(x=>x.id===row.id);assert.equal(archived.status,'Eliminado');assert.equal(archived.total,34120);assert.equal(archived.updatedBy,'Valentina');assert.match(archived.notes,/Duplicada/);assert.match(archived.notes,/estadoAnterior/);
 assert.equal(f.call('deleteSale',{id:row.id,version:1,reason:'Duplicada'},'admin').alreadyDeleted,true);assert.throws(()=>f.call('updatePayment',{id:row.id,version:2,status:'Pagado'}),/eliminada/);assert.throws(()=>f.call('saveOrder',order),/eliminado/);assert.equal(f.ctx.REQUEST_ROLE_,null);
});
test('deleting a settled row preserves settlement audit and handles blank physical rows',()=>{const f=roles();f.call('saveOrder',f.order());const row=f.call('getData').sales[0];f.call('settleSales',{requestId:'settle-one',ids:[row.id],versions:[1],date:'2026-09-13',notes:''});const s=f.db.getSheetByName('ML_Ventas');s.rows.splice(1,0,[]);f.call('deleteSale',{id:row.id,version:2,reason:'Registro incorrecto'},'admin');assert.equal(s.rows[1].length,0);assert.equal(s.rows[2][14],'Eliminado');assert.equal(s.rows[2][21],'settle-one');assert.equal(f.call('getData').sales.length,0);});
